# Generated by Django 3.2.6 on 2021-08-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
